echo '---------------------------------------------------------------------'
echo 'List of ThinkLP SFDX Commands:'
echo
echo 'push                  (To push project to scratch org)'
echo 'test                  (To run a specific tests)'
echo 'push_test             (To push the code before running the tests)'
echo 'retrieve              (To retrieve specific metadata types from scratch to project)'
echo 'pull                  (Similar to retrieve but does not pull CustomLabels)'
echo 'core_scratch          (To create a scratch org for the Core package)'
echo 'auth_dev_hub          (To authorize the dev hub on your machine)'
echo 'help_me               (To display the list of ThinkLP SFDX Commands)'
echo '---------------------------------------------------------------------'